Catch no arguments being passed. Closes #1

diff --git a/argon1-ubuntu b/argon1-ubuntu
--- a/argon1-ubuntu
+++ b/argon1-ubuntu
@@ -281,26 +281,31 @@ function uninstall_argonone() {
 }
 
 # Take command line arguments
-while [ $# -gt 0 ]; do
-  case "${1}" in
-    -config|--config)
-      shift
-      config_argonone
-      exit 0;;
-    -install|--install)
-      shift
-      install_argonone
-      exit 0;;
-    -uninstall|--uninstall)
-      shift
-      uninstall_argonone
-      exit 0;;
-    -h|--h|-help|--help)
-      usage
-      exit 0;;
-    *)
-      echo "[!] ERROR: \"${1}\" is not a supported parameter."
-      usage
-      exit 1;;
-  esac
-done
+if [ $# -lt 1 ]; then
+    usage
+    exit 0
+else
+    while [ $# -gt 0 ]; do
+        case "${1}" in
+            -config|--config)
+            shift
+            config_argonone
+            exit 0;;
+            -install|--install)
+            shift
+            install_argonone
+            exit 0;;
+            -uninstall|--uninstall)
+            shift
+            uninstall_argonone
+            exit 0;;
+            -h|--h|-help|--help)
+            usage
+            exit 0;;
+            *)
+            echo "[!] ERROR: \"${1}\" is not a supported parameter."
+            usage
+            exit 1;;
+        esac
+    done
+fi
